steps:
- name: 'python:3.9'
  entrypoint: pip
  args: ['install', 'poetry']

- name: 'python:3.9'
  entrypoint: poetry
  args: ['install']

- name: 'python:3.9'
  entrypoint: poetry
  args: ['run', 'pytest']

- name: 'python:3.9'
  entrypoint: poetry
  args: ['build']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'dist/*', 'gs://YOUR_BUCKET_NAME/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'update-container', 'get-attractions-instance', 
         '--container-image=gcr.io/cloud-builders/gcloud',
         '--container-command=sh,-c,pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev && poetry run get-attractions',
         '--zone=us-central1-a']